### ISSUE TITLE
Registration my app is not working in Centricity Developer Portal

### ISSUE THREAD

**Issue by Jagshealthasyst** [GEHealthcare/apiserver.gehealthcare.com#10]
Registration my app is not working in Centricity Developer Portal.
https://mydata.gehealthcare.com/registration

**Comment by kumarsatyam02** [comment]
I just tried registering an App. It worked fine for me. !! Would you please try once again,  Please be sure to disable popup blocker in your browser.

**Comment by Jagshealthasyst** [comment]
Yes Satyam. It works from outside the network. I will work with IT team. 

Thanks.
