### ISSUE TITLE
Application Registration without Global Admin

### ISSUE THREAD

**Issue by JayJMobley** [GEHealthcare/apiserver.gehealthcare.com#12]
I have some concerns as a VAR that customers who need JBOSS reinstalled in the middle of the night in a disaster recovery type scenario.. that I am not going to be able to re-connect their JBOSS instance to Azure without access to the Global Admin account. 

I understand the need for Global Admin to _create_ the applications in Azure, but Once the application has been created in Azure AD is there any way of reconnecting JBOSS to those applications w/o the Global Admin account.

**Comment by keithboone** [comment]
Yes, there is.  The key is to maintain a backup of the deployments folder under JBoss, and to restore the contents of that folder after JBoss is reinstalled.

                Keith

**Comment by JayJMobley** [comment]
If you could provide specifics on what needs to be backed up that would be preferable. Often times, in the field,  we have to reinstall the JBOSS site because AD auth starts failing for some undetermined reason or the SOLR cache gets out of whack and causes the CPS client to crash anytime a user tries to search for a problem. These are just a few illustrative examples. My fear is that restoring the entire back up in such a scenario would re-introduce whatever issue we’re trying to battle.

Jay J. Mobley
Clinical Applications Support Manager
HealthCo Information Systems   |   Partner GE HealthCare
p 888-740-7734   |   f 503-597-3723
www.healthcosystems.com<http://www.healthcosystems.com/>
[Asset 1]<https://www.healthcosystems.com/about/recognition/>

**Comment by keithboone** [comment]
AAD Configuration information is primarily stored in <dbName>APIServer.war\WEB-INF\classes\resources\security and below.

                Keith

**Comment by JayJMobley** [comment]
Good stuff, Keith.. thanks!! I’ll test that out and see what we get!

Jay J. Mobley
Clinical Applications Support Manager
HealthCo Information Systems   |   Partner GE HealthCare
p 888-740-7734   |   f 503-597-3723
www.healthcosystems.com<http://www.healthcosystems.com/>
[Asset 1]<https://www.healthcosystems.com/about/recognition/>

**Comment by JayJMobley** [comment]
Just wanted to report that after reinstalling JBOSS and restoring the contents of <dbName>APIServer.war\WEB-INF\classes\resources\security and below. I was not able to restore previously functional CCDA2.1 generation.

**Comment by SameerSingh1991** [comment]
Closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
