### ISSUE TITLE
Upgrade of JBOSS causes API server deployment to fail

### ISSUE THREAD

**Issue by JayJMobley** [GEHealthcare/apiserver.gehealthcare.com#13]
**Describe the bug**
After upgrading 12.3.1 to 12.3.2 - I re-ran the AAD scripts to connect them back into my AAD Registered APPs. After successfully running the scripts my API server would not deploy. 

**To Reproduce**
1. have a working 12.3.1 install w/ AAD scripts ran and all deployments successfully deployed
2. upgrade CPS12.3.1 to CPS 12.3.2 (including JBOSS site upgrade)
3. Re-run Azure AD scripts
4. Check JBOSS C:\Program Files\Centricity Practice Solution\jboss\standalone\deployments  see API server is in a .failed deployment 

**Expected behavior**
API server should be .deployed

**Screenshots**

**Desktop (please complete the following information, if applicable):**
 - OS: Windows Server 2012 R2
 - Browser Chrome/IE
 - Version Chrome is 68.0.3440.84 / IE 11

**Smartphone (please complete the following information, if applicable):**
n/a

**Additional context**
After troubleshooting I found that if I renamed the C:\Program Files\Centricity Practice Solution\jboss\standalone\data\fv and re-ran the AAD scripts my API server deployed successfully.

**Comment by kumarsatyam02** [comment]
Thank you for reporting the issue and a workaround.

**Comment by SameerSingh1991** [comment]
Closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
