### ISSUE TITLE
requesting a patient's appointments

### ISSUE THREAD

**Issue by eluchetti** [GEHealthcare/apiserver.gehealthcare.com#17]
**Your question**

How can I ask FHIR for a patient's Appointments?

**Any background information about this question**

I already tried this but this endpoint 
https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir/Patient/1841438950893400/Appointment
but the response is 
`{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>PROCESSING</td><td>Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Patient/1841438950893400/Appointment] with parameters [[_format]]</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Patient/1841438950893400/Appointment] with parameters [[_format]]"
        }
    ]
}`

thanks in advance

**Comment by eluchetti** [comment]
I've found that this request is correctly handled instead. 

https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir/Appointment?_format=json&patient=1841478950893400

but there doesn't seem to be any user with appointments. 
so i'm wondering if the call is correct , in this case would it be possible to have at least one appointment to test on that?

or in alternative, which would be much more effective to our scenario, would it be possible to be advised on the correct process for posting an appointment by ourselves?

thanks in advance

emanuele

**Comment by SameerSingh1991** [comment]
Please reopen if you still encounter this issue.
