### ISSUE TITLE
search Patient List

### ISSUE THREAD

**Issue by eluchetti** [GEHealthcare/apiserver.gehealthcare.com#18]
**Your question**

Is it possible to get a token with an admin profile such as to be allowed to get the list of patients?

How would the authorization steps change accordingly?
thanks in advance

**Comment by kumarsatyam02** [comment]
Yes, it is possible to get a token for any valid user on the system. Token scope depends upon user's privileges. Steps do not change.

**Comment by eluchetti** [comment]
when I follow the steps to authenticate with the Sample work account credentials hwinston@sboxprovtenant.com / TestProvider!@ then I'm forced to chose a patinet from a list an then I receive a token for consuming resources as that particular patient. how can I receive a token to act as the work account himself?

thanks in advance

**Comment by keithboone** [comment]
When you make the request using the launch/patient scope, you will go through the patient selection process as described in the SMART on FHIR specification<http://docs.smarthealthit.org/authorization/scopes-and-launch-context/>.  If you remove that scope from the launch process, you should just be able to make queries.  If you are using the patient/* scopes, you should instead request user/* scopes.

                Keith

**Comment by eluchetti** [comment]
Thank you very much
