### ISSUE TITLE
Where to find sample account information?

### ISSUE THREAD

**Issue by speakingcode** [GEHealthcare/apiserver.gehealthcare.com#22]
https://mydata.gehealthcare.com/access-centricity-apis says:

> When you register my application, you will be given a sample work and personal account to test with.

This does not appear to be the case. Where can I find this information? Looking at My Apps in the Dev Center does not show any account details

**Comment by eluchetti** [comment]
Sample work account credentials
hwinston@sboxprovtenant.com / TestProvider!@
Sample personal account credentials
walter.caldwell@outlook.com / TestPatient!@

**Comment by SameerSingh1991** [comment]
Please reopen if you still encounter this issue.
