### ISSUE TITLE
 fetch all the patients and appointments records

### ISSUE THREAD

**Issue by ShubhamRaj2011** [GEHealthcare/apiserver.gehealthcare.com#273]
Can someone guide me on how to fetch all the patients and appointment records?

I have done the authentication process as mentioned here https://mydata.athenahealth.com/access-the-apis

I am a little lost, after authentication how to call the APIs

**Comment by AjeetYadav07** [comment]
After creating an access token, you have to use that access token as bearer token to call our supported APIs. like for patient https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Appointment?patient=1442678380550620. Similar way you can call other APIs as well.

**Comment by AjeetYadav07** [comment]
@ShubhamRaj2011 Closing this issue, if you have any query further please raise a new ticket.
