### ISSUE TITLE
Work Account Creation on sandbox

### ISSUE THREAD

**Issue by ShubhamRaj2011** [GEHealthcare/apiserver.gehealthcare.com#275]
How can we create work account (provider workflow) in sandbox env?

Plus where can I login and add test patients and appointment records.

**Comment by AjeetYadav07** [comment]
Hi @ShubhamRaj2011
Devportal documentation having all the details to the create an account and access our APIs supported. please refer https://mydata.athenahealth.com/access-the-apis

**Comment by AjeetYadav07** [comment]
Hi @ShubhamRaj2011, hoping we have answered your question. Marking this issue as closed, please raise a new ticket if you have any query further.
