### ISSUE TITLE
I wanted to try athena health sandbox endpoints. After generation of clientId and clientSecret , when clicked on authorize button in athena health, I am getting access denied error 

### ISSUE THREAD

**Issue by Ishapiplatform** [GEHealthcare/apiserver.gehealthcare.com#276]
**Your question**

For example, How do I....?

**Any background information about this question**

For example, I need to be able to access xyz from abc but the API doesn't seem to support this.....

**Comment by athena-Interop** [comment]
@Ishapiplatform

Please post a copy of the full URL you are using for the authorize endpoint of the FHIR Server.

Please post a screenshot and give more information where you are seeing authorize button.

This GitHub support forum is used for athenaPractice and athenaFlow products.

There are different contacts for help with athenaOne.
Use https://docs.athenahealth.com/api/ for API integration with athenaOne.

Use https://docs.athenahealth.com/api/support to resubmit this request to get answers to your questions about athenaOne APIs.

**Comment by AjeetYadav07** [comment]
@Ishapiplatform,
Hoping we have addressed your queries, marking this issue as closed.
