### ISSUE TITLE
How do I launch the app in the embedded flow?

### ISSUE THREAD

**Issue by subbu-clustrex** [GEHealthcare/apiserver.gehealthcare.com#278]
I have created an app on https://mydata.athenahealth.com/. I am able to get the access_token using the OAuth2 flow.
https://mydata.athenahealth.com/access-the-apis

Now I want to do this in the embedded flow. Could you please help me to develop it in embedded flow?

**Comment by Torin-Shepard-athena** [comment]
Please clarify and add more technical details about what you mean by embedded flow.
Are the comments in issue #214 applicable to the "embedded flow" use case or scenario you are asking about?

**Comment by deepaktiwari29** [comment]
@subbu-clustrex 
Marking as closed since there hasn't been any explanation on the issue. Please register a new issue, If you are having any query.
