### ISSUE TITLE
Unable to get Authorization code

### ISSUE THREAD

**Issue by Deiva1** [GEHealthcare/apiserver.gehealthcare.com#279]
Hi,
Greetings!

  I have created an App in Athenahealth developer portal and got the Client ID and Client Secret. I tried generating Authorization endpoint with the help of API access document.
But I got this error output, How to sort this out. Kindly, provide step by step procedure to access the FHIR API

![image](https://github.com/athenahealth/apiserver-athenaFlex/assets/126863526/fb233bc2-982a-402a-92e6-0050d67c5bcd)

**Comment by athena-Interop** [comment]
The ap22sandbox machine needed some maintenance. Please try again.  If you still have trouble please post a full copy of the URL you are using for the authorize endpoint.

**Comment by Deiva1** [comment]
Still having the same issue in fetching the Authorization code. Here, is the full URL for reference
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&
scope=openid%20profile%20patient/*.read%20launch/patient&
response_type=code&
redirect_uri=https://localhost/athenahealth/code.php&
aud=https%3A%2F%2Fap22sandbox.fhirapi.athenahealth.com%2FdemoAPIServer&
client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL2Voci5jYXBtaW5kcy5jb20iLCJncmFudF90eXBlcyI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwiaXNzIjoiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tIiwicmVkaXJlY3RfdXJpcyI6WyJodHRwczpcL1wvbG9jYWxob3N0XC9hdGhuYWhlYWx0aFwvY29kZS5waHAiXSwidG9rZW5fZW5kcG9pbnRfYXV0aF9tZXRob2QiOiJjbGllbnRfc2VjcmV0X2Jhc2ljIiwic29mdHdhcmVfaWQiOiI3LjAuMCIsIm5hdGl2ZV9jbGllbnQiOmZhbHNlLCJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb21cL29hdXRoMi5jbGFpbXNcL2FwcF9pZCI6IjZkYTZjMjg4LTgzMTktNDgxOC1hMzNkLTdhZDgyZDYxODJjZCIsImV4cCI6MjAwOTYxNTczOSwiY2xpZW50X25hbWUiOiJEZW1vX0FQSSIsImlhdCI6MTY5Mzk5NjUzOSwiY29udGFjdHMiOlsiZGVpdmFuYWl0aGlhZ2FyYWphbkBnbWFpbC5jb20iXSwicmVzcG9uc2VfdHlwZXMiOlsiY29kZSJdfQ.LYGaNNkir0Cwe5TZ-vz6dYFPs3ouNC8nvuat3PBhgz0zCFvM_9KL5YqURidenD6S8ikUnJs_d6rAHUUJd87Jstg3orJqGmsrltobwqGhw7iIceHri3d8161kHguDwSSjierGn7tFkJbcd7phZxWI54oLrrHfWeAShZGeQ84uhSU

**Comment by athena-Interop** [comment]
Hi ,

I tried with test credentials, and I can get the login screen. Can you please reverify your ClientID and redirect uri once. Please check for wanted spaces as well.

Regards,
Laxmi

**Comment by athena-Interop** [comment]
@Deiva1
The authorizeURL redirect_uri parameter value must match one of the redirect URLs registered with your ClientID.

The authorize URL you attempted has redirect_uri=https://localhost/**athenahealth**/code.php
Your ClientID is registered with a different value where the e is missing: https://localhost/**athnahealth**/code.php
Please remove the letter e and use athnahealth in the redirect_uri parameter your authorize request.

Changing values of applications registered at the mydata.athenahealth.com Dev Portal is not supported.  If you want or need to change the redirect URL, you will need to register a new application and get a new ClientID.

**Comment by Deiva1** [comment]
Successfully fixed the issue, Thanks.

can you share the documentation to add and fetch full patient data with
clinical records API in AthenaHealth.

Unable to use client ID again once we got the Authorization code
![image](https://github.com/athenahealth/apiserver-athenaFlex/assets/126863526/9cb0611a-2154-4e5c-8fc6-93421ecb979c)

**Comment by athena-Interop** [comment]
You can search previous issues for information about sample patients and sample data available in the demonstration databases used by the FHIR Servers on the athenaPractice API Sandbox machines.
https://github.com/athenahealth/apiserver-athenaFlex/issues?q=is%3Aissue+sample+data
Comments in the following issues have identifiers for sample patient, clinical, and practice managements resoures.
#114
#117
#144
#141
#184


Search for post, create, put, update to find issues related to FHIR write APIs.
https://github.com/athenahealth/apiserver-athenaFlex/issues?q=is%3Aissue+post
https://github.com/athenahealth/apiserver-athenaFlex/issues?q=is%3Aissue+create
https://github.com/athenahealth/apiserver-athenaFlex/issues?q=is%3Aissue+post+create
https://github.com/athenahealth/apiserver-athenaFlex/issues?q=is%3Aissue+put+update

The following issues have information about some of the FHIR Server write capabilities
#197
#231
#271
#272
#224
#234
#262
#168
#204
#209

**Comment by AjeetYadav07** [comment]
@Deiva1,

Hoping we have addressed all queries in this ticket, Marking this issue as closed. If you have any query please raise a new ticket.
