### ISSUE TITLE
Failed to Search Patient in the OAuth2.0 Flow

### ISSUE THREAD

**Issue by prithivi-clustrex** [GEHealthcare/apiserver.gehealthcare.com#280]
**Describe the bug**
Not able to search the patient. Previously it worked well now the patient search results not showing

**To Reproduce**

1. Try OAuth2.0 in Postman or Web UI

**Expected behavior**
A list of patients will be displayed based on search criteria. Then the provider has to select one patient

**Screenshots**
![image](https://github.com/athenahealth/apiserver-athenaFlex/assets/29299221/2c45fdab-be8b-49dd-8392-bb9a1e23b534)

**Desktop (please complete the following information, if applicable):**
 - OS: Windows
 - Browser: Chrome
 - Version: 116.0.5845.141 (Official Build) (64-bit)

**Comment by deepaktiwari29** [comment]
@prithivi-clustrex Is this issue still re-producible? As we are able to search for patients using both the web UI and Postman.

**Comment by deepaktiwari29** [comment]
Hello @prithivi-clustrex, Marking this issue as closed as there are no follow up questions. If there are any queries, please register a new issue.

**Comment by deepaktiwari29** [comment]
Hello @prithivi-clustrex, Marking this issue as closed as there are no follow up questions. If there are any queries, please register a new issue.
