### ISSUE TITLE
Unable to retrieve allergy, procedure, diagnosis, and all medication-related data for a patient's specific encounter

### ISSUE THREAD

**Issue by balamurugan-clustrex** [GEHealthcare/apiserver.gehealthcare.com#282]
Description:
I am experiencing issues when attempting to retrieve allergy, procedure, diagnosis, and all medication-related data for a patient's specific encounter.

Steps to Reproduce:
Use OAuth2.0 in Postman or a Web UI.

Expected Behavior:
I expect to receive allergy, procedure, diagnosis, and all medication-related data for a patient's specific encounter.

Additional Information:
I have tried with different patients, but I am unable to retrieve the data.
I would greatly appreciate any assistance or guidance in resolving this issue. Please provide me with the patient ID and encounter ID I need for this purpose.

**Comment by deepaktiwari29** [comment]
Hello @balamurugan-clustrex ,
Is this issue still reproducible? If yes, please provide us more information so we can help with your issues.

**Comment by deepaktiwari29** [comment]
Hello @balamurugan-clustrex, Marking this issue as closed as there are no follow up questions. If there are any queries, please register a new issue.
