### ISSUE TITLE
Unable to create the patient using API 

### ISSUE THREAD

**Issue by balamurugan-clustrex** [GEHealthcare/apiserver.gehealthcare.com#283]
Description:
I am unable to create the patient but I got an invalid scope error.

Steps to Reproduce:
Use OAuth2.0 in Postman or a Web UI.

Expected Behavior:
I wish to create the patient.

Additional Information:
I have tried with scopes patient/*.*, patient/*.* launch, and patient/*.* launch/patient, but I cannot create the patient.
I would greatly appreciate any assistance or guidance in resolving this issue.

URL : https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Patient

**Comment by AjeetYadav07** [comment]
@balamurugan-clustrex 

To write the data using Patient resource, scope should set to either user/Patient.write or patient/Patient.write. Please select appropriate scope to use the FHIR resource endpoints.

**Comment by AjeetYadav07** [comment]
@balamurugan-clustrex, 
Marking this issue as closed, please register new issues for future queries.
