### ISSUE TITLE
unable to create the appointment against the patient using API

### ISSUE THREAD

**Issue by balamurugan-clustrex** [GEHealthcare/apiserver.gehealthcare.com#284]
Description:
I am unable to create the appointment against the patient.

Steps to Reproduce:
Use OAuth2.0 in Postman or a Web UI.

Expected Behavior:
I wish to create the patient.

Additional Information:
I have tried to create the appointment against the patient, but I am unable to create it.
I got this error:
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>BUSINESSRULE</td><td>Location Participant is mandatory</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Location Participant is mandatory"
        }
    ]
}
I would greatly appreciate any assistance or guidance in resolving this issue.

URL : https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Appointment

body:

{
    "resourceType": "Appointment",
    "id": "Example2",
    "serviceType": [
        {
            "coding": [
                {
                    "system": "https://docs.mydata.athenahealth.com/fhir-r4/CodeSystem/athena-appointment-service-type.html",
                    "code": "5",
                    "display": "Established Patient-New Problem "
                }
            ],
            "text": "Established Patient-New Problem "
        }
    ],
    "reasonCode": [
        {
            "text": "chronic pain, right wrist"
        }
    ],
    "description": "Established Patient-New Problem",
    "start": "2012-03-20T08:45:00.000+05:30",
    "end": "2012-03-20T09:15:00.000+05:30",
    "minutesDuration": 30,
     "comment": "chronic pain, right wrist",
    "participant": [
        {
            "actor": {
                "reference": "Patient/126230400001500"
            },
            "status": "tentative"
        },
        {
            "type": [
                {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/v3/ParticipationType",
                            "code": "PPRF",
                            "display": "primary performer"
                        }
                    ],
                    "text": "primary performer"
                },
                {
                    "coding": [
                        {
                            "system": "http://hl7.org/fhir/ValueSet/c80-practice-codes",
                            "code": "394601005",
                            "display": "Physical Therapy"
                        }
                    ],
                    "text": "Physical Therapy"
                }
            ],
            "actor": {
                "reference": "Practitioner/1225652472001060"
            },
            "status": "tentative"
        },
        {
            "actor": {
                "reference": "Location/1225648184001060"
            },
            "status": "tentative"
        },
        {
            "type": [
                {
                    "coding": [
                        {
                            "system": "https://docs.mydata.athenahealth.com/fhir-r4/athenaFlex/codesystem/PARTICIPANTTYPECPS",
                            "code": "Resource",
                            "display": "Resource"
                        }
                    ],
                    "text": "Resource"
                }
            ],
            "actor": {
                "reference": "Practitioner/1225652472001060"
            },
            "status": "tentative"
        }
    ]
}

**Comment by AjeetYadav07** [comment]
@balamurugan-clustrex,

Please refer to the https://github.com/athenahealth/apiserver-athenaFlex/issues/286, explained the details on location participant issue.

**Comment by deepaktiwari29** [comment]
Hello @balamurugan-clustrex, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
