### ISSUE TITLE
Unable to use charge and claim FHIR api in mydata.athenahealth

### ISSUE THREAD

**Issue by kabilan-rk** [GEHealthcare/apiserver.gehealthcare.com#287]
Unable to use charge and claim FHIR api in mydata.athenahealth i tried using the api endpoint provided in fhirapidoc

https://mydata.athenahealth.com/fhirapidoc/r4

Are there any other api endpoints other than https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/<......>

**Comment by AjeetYadav07** [comment]
@kabilan-rk 

Charge and claim FHIR api is available from version 23 onwards. The sandbox you are looking is for version 22. please use version 23 sandbox to access listed custom resources https://mydata.athenahealth.com/fhirapidoc/r4

In the access token header scope parameter tells about which api's can be accessed.

Version 23 Sandbox : 
https://ap23sandbox.fhirapi.athenahealth.com/demoAPIServer/customresource/Charge?{search-param}

**Comment by kabilan-rk** [comment]
@AjeetYadav07  thanks for the reply I am able to access charge and claim in 23 sandbox.
How do we associate a particular charge with an appointment or encounter ?
In ap23 sandbox I am able to get a charge for a patient with no appointments.

**Comment by deepaktiwari29** [comment]
@kabilan-rk 
Currently we are not supporting association of charge with an appointment/encounter through FHIR APIs.
Please refer the attached Charge Resource example: https://docs.mydata.athenahealth.com/fhir-r4/Charge-Example1.json

**Comment by deepaktiwari29** [comment]
Hello @kabilan-rk, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
