### ISSUE TITLE
unable to login getting error - session_expired or invalid_state Your session timed out or the authorization request was invalid.

### ISSUE THREAD

**Issue by daman9646** [GEHealthcare/apiserver.gehealthcare.com#288]
unable to login getting error - session_expired or invalid_state Your session timed out or the authorization request was invalid.

**To Reproduce**
1 Construct the url and open in browser
2 click on work account 
3 login with hwinston@sboxprovtenant.com , TestProvider!@

**Expected behavior**
Patient search screen

![Uploading Screenshot 2024-01-09 at 10.53.08 AM.png…]()

**Comment by ThomasNYoung** [comment]
I am getting the same error with those same credentials after building the url.
`Oops!
session_expired or invalid_state
Your session timed out or the authorization request was invalid.`

This is for Provider workflow.

**Comment by deepaktiwari29** [comment]
Hello @daman9646 & @ThomasNYoung,
I am able to get the code and generate token on ap22 sandbox. Were you able to follow the instructions from dev portal and get the appropriate auth code after selecting the patient? If not, can you please post a full copy of the URL you are using for the authorize endpoint.

**Comment by deepaktiwari29** [comment]
Hello @daman9646 & @ThomasNYoung, hoping you are not facing this still. Marking this issue as closed, if you have any further questions, please open a new ticket.
