### ISSUE TITLE
wosc

### ISSUE THREAD

**Issue by daman9646** [GEHealthcare/apiserver.gehealthcare.com#289]
How can we grant access to the WOSC patients only?

**Comment by athena-Interop** [comment]
This forum provides support for the on premise athenaPractice/athenaFlow FHIR APIs.

Please use https://docs.athenahealth.com/api/support for assistance with cloud-based athenaOne/athenaClinicals APIs.

**Comment by deepaktiwari29** [comment]
Hello @daman9646, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
