### ISSUE TITLE
wosc

### ISSUE THREAD

**Issue by daman9646** [GEHealthcare/apiserver.gehealthcare.com#290]
Can athena provide access to Friday surgery patients only? or WOSC site only?
Or can the staff provide information on the patients manually?

**Comment by athena-Interop** [comment]
@daman9646 
This forum provides support for the on premise athenaPractice/athenaFlow FHIR APIs.

Please see https://docs.athenahealth.com/api/support for assistance with cloud-based athenaOne/athenaClinicals APIs.

If you are integrating with aP/aF, please explain and clarify the question.  What is meant by Friday surgery patients or WOSC site?  aP/aF FHIR default sandbox/demonstration database does not have WOSC as the abbreviation for any FHIR Location or Organization resources.

**Comment by deepaktiwari29** [comment]
Hello @daman9646, closing this issue, if you have any query further please raise a new ticket.
