### ISSUE TITLE
Configuration/Implementation Guide

### ISSUE THREAD

**Issue by nkagal** [GEHealthcare/apiserver.gehealthcare.com#291]
**Your question**

Can I please get a copy of your configuration and/or implementation guide that is shared with customers?

**Any background information about this question**

**Comment by deepaktiwari29** [comment]
Hello @nkagal,
The configuration & implementation of aP/aF product related to FHIR R4 APIs are listed in below URL:
https://mydata.athenahealth.com/fhirapidoc/r4

**Comment by deepaktiwari29** [comment]
Hello @nkagal, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
