### ISSUE TITLE
Clarity on APIs

### ISSUE THREAD

**Issue by ganeshshetty-uas** [GEHealthcare/apiserver.gehealthcare.com#292]
1)	Identifying the appropriate Athena APIs required for retrieving fields indicated in Yellow in the attached document.
2)	According to our current understanding, the available search criteria for extracting accounts from Athena APIs are as follows. Is there a method to retrieve all accounts that meet specific criteria, such as amount due, last payment date/age of debt, or for a given service provider/facility?
a.	Search Criteria for Athena API - {"fields":["guarantorfirstname","lastname","mobilephone","guarantormiddlename","firstname","middlename","departmentid","dob","guarantorsuffix", "suffix","workphone","homephone","guarantorlastname","anyphone"]
[Retrieval Apps - Athena API Field Mapping - 01122024.xlsx](https://github.com/athenahealth/apiserver-athenaFlex/files/14141160/Retrieval.Apps.-.Athena.API.Field.Mapping.-.01122024.xlsx)

**Comment by athena-Interop** [comment]
@ganeshshetty-uas 
apiserver-athenaFlex forum provides support for the on premise athenaPractice/athenaFlow (aP/aF) FHIR APIs.

"Athena API" column in the spreadsheet you attached shows patients/1124.  This appears to be one of the APIs for athenaOne platform.

aP/aF has FHIR Patient API but does not have any "patients" API.  Search parameters for each FHIR API are listed on the pages for each FHIR resource type at https://mydata.athenahealth.com/fhirapidoc/r4

Please see https://docs.athenahealth.com/api/support for assistance with cloud-based athenaOne APIs.

If you are integrating with aP/aF, please explain and clarify your question in terms of FHIR APIs.

**Comment by deepaktiwari29** [comment]
Hi @ganeshshetty-uas, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
