### ISSUE TITLE
Correct way to cancel an appointment

### ISSUE THREAD

**Issue by schlueterryan** [GEHealthcare/apiserver.gehealthcare.com#294]
I want to verify that I am cancelling appointments correctly. It looks like my slot is still showing as held even after cancelling the appointment. 

I am doing a Put Request changing the status of the appointment to cancelled. Is there anything else I need to do there?

**Comment by kdevine** [comment]
They reference that this was fixed in v22, but it appears to still be broken.  Reference Issue 194.

**Comment by schlueterryan** [comment]
@AjeetYadav07 I think this might be the more important one to focus on and might be causing more issues with the creating in different slots. Is there anything we can try to get the cancel to work? It is failing to release the slot on every request.

**Comment by AjeetYadav07** [comment]
@schlueterryan,

We offer two ways to cancel your appointment: with or without requesting an extension.

Please take a look at the cancel appointments payload provided below. 

Once you've successfully canceled the appointment, be sure to log out completely from the CPS client application, refresh the slot availability on the chart screen. This will ensure that the canceled slot is released and becomes available for booking again.

[appt_with_ext.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/14847952/appt_with_ext.txt)
[appt_wothout_ext.txt](https://github.com/athenahealth/apiserver-athenaFlex/files/14847962/appt_wothout_ext.txt)

**Comment by schlueterryan** [comment]
I did have mine setup as your second example, I just tried the first example and it's still not releasing the slot.

The APPOINTMENT shows a status of Canceled but the SLOT is still busy - Occupied by an appointment

Here is how its still showing the slot having the appointmentId in the database:

![unnamed (1)](https://github.com/athenahealth/apiserver-athenaFlex/assets/5241146/3b4e3ef5-3370-45f7-8eb9-e08872e094db)
![unnamed (2)](https://github.com/athenahealth/apiserver-athenaFlex/assets/5241146/bf623727-8150-43c5-a5d3-5d7730fa3055)

**Comment by schlueterryan** [comment]
According to the Metadata endpoint we are on version - 1.23.5095 that should be up to date enough to not be running into this issue correct? 

https://github.com/athenahealth/apiserver-athenaFlex/issues/194#issuecomment-1034149915

**Comment by AjeetYadav07** [comment]
@schlueterryan,

When appointment shows a status of Canceled, it will remove the entry from apptslot table for corresponding appointmentsId like in below. 
<img width="627" alt="image" src="https://github.com/athenahealth/apiserver-athenaFlex/assets/68940876/c3e0794b-e846-47bd-b9ac-66faf4539922">

**Comment by schlueterryan** [comment]
@AjeetYadav07 
That's the problem it's not removing that entry. As you can see in my posted image its not removing that row even though it's showing Cancel/Patient. Is there anything we can change on this side to make sure it removes the slot from the appointment?

**Comment by rashmi1977** [comment]
This issue is addressed in upcoming release which is V25 which will be available for customers during first quarter of 2025.

**Comment by schlueterryan** [comment]
@rashmi1977 is there any known workarounds or is it just broken for the next year?

**Comment by rashmi1977** [comment]
@schlueterryan : We need to manually delete the booking in the ApptSlot table in DB in so that the slot is released for further booking. After deleting the record we need to restart JBoss.We have verified this workflow and have seen that once the Appointment is deleted the slot is released in UI. As of now we have this workaround but this issue has been addressed in V25 release.

**Comment by deepaktiwari29** [comment]
Hello @schlueterryan, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
