### ISSUE TITLE
Vitals Post

### ISSUE THREAD

**Issue by vx-jose** [GEHealthcare/apiserver.gehealthcare.com#296]
Having difficulty with posting a vitals sign to a chart

Per documentation:

https://docs.athenahealth.com/api/workflows/vitals-charts-overview#Adding_Device_Generated_Vitals_3

Even tried using vitals example:

[  [ { "clinicalelementid" : "VITALS.TEMPERATURE", "readingtaken" : "01/01/2016", "value": "98.6" } ] ]

But even with using this payload I get an error that it is not JSON?

Here is the developed curl:

curl -X 'POST' \
  'https://api.preview.platform.athenahealth.com/v1/195900/chart/1670/vitals' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer Q1225FCRXXXXXXXXXXXXXX' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'PATIENTFACINGCALL=&THIRDPARTYUSERNAME=&departmentid=1&returnvitalids=&source=DEVICEGENERATED&vitals=%5B%5B%22%7B%5C%22vitals%5C%22%3A%20%5B%5B%20%7B%20%5C%22clinicalelementid%5C%22%20%3A%20%5C%22VITALS.TEMPERATURE%5C%22%2C%20%5C%22value%5C%22%3A%20%5C%2298.6%5C%22%20%7D%20%5D%20%5D%7D%22%5D%5D'

The question I have, can someone provide an example of the vitals format that I should be using?

Thanks!

**Comment by deepaktiwari29** [comment]
Hello @vx-jose,

This GitHub support forum is used for athenaPractice and athenaFlow products.

There are different contacts for help with athenaOne.
Use https://docs.athenahealth.com/api/ for API integration with athenaOne.

Use https://docs.athenahealth.com/api/support to resubmit this request to get answers to your questions about athenaOne APIs.
