### ISSUE TITLE
I'm having a hard time getting an access code trying to to through the setup

### ISSUE THREAD

**Issue by GaryHammer701** [GEHealthcare/apiserver.gehealthcare.com#297]
This is to set up an authorized API in the support lab (Richardton data center)

I tried following the directions and get an invalid audience parameter response with this URL

https://acmsptc14762001.devathenahealthcloud.com:9443/demoAPIServer/oauth2/authorize?state=defaultState&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code&redirect_uri=https://youtube.com&aud=https%3A%2F%2Facmsptc14762001.devathenahealthcloud.com/demoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cHM6XC9cL3lvdXR1YmUuY29tIiwiZ3JhbnRfdHlwZXMiOlsiYXV0aG9yaXphdGlvbl9jb2RlIl0sImlzcyI6Imh0dHBzOlwvXC9teWRhdGEuZ2VoZWFsdGhjYXJlLmNvbSIsInJlZGlyZWN0X3VyaXMiOlsiaHR0cHM6XC9cL3lvdXR1YmUuY29tXC9yZWRpcmVjdCJdLCJ0b2tlbl9lbmRwb2ludF9hdXRoX21ldGhvZCI6ImNsaWVudF9zZWNyZXRfYmFzaWMiLCJzb2Z0d2FyZV9pZCI6IjEuMWEiLCJuYXRpdmVfY2xpZW50IjpmYWxzZSwiaHR0cHM6XC9cL215ZGF0YS5nZWhlYWx0aGNhcmUuY29tXC9vYXV0aDIuY2xhaW1zXC9hcHBfaWQiOiJjNWI3YThhZS04YjQyLTQ4NTItOWU2OS0yYWNlOWZmNDBmMTQiLCJleHAiOjE5OTE0MDgyMTgsImNsaWVudF9uYW1lIjoiRmViMjAyM3YyM1Rlc3QxIiwiaWF0IjoxNjc1Nzg5MDE4LCJjb250YWN0cyI6WyJoYW1tZXI5N0Bob3RtYWlsLmNvbSJdLCJyZXNwb25zZV90eXBlcyI6WyJjb2RlIl19.vzQR6qZ51dDveoZcvZZayKpVAx5sr8m0n_UbYStq6bDMJ_ZTa58ant-SGQ7LJ93K52fNouubIf1Mm2t-MFPXHPGMut4FT5v4pJKiTdFc-KbU1naN-Cn3uLUGs6dx5SBXh1knDmm8UCO7mwJZ-99O3hjFXx02vWvPIJR7VdUDXc4

**Comment by deepaktiwari29** [comment]
Hello @GaryHammer701,

Please try using /fhir/r4 as the audience for the authorize URL.
Use either aud=https%3A%2F%2Facmsptc14762001.devathenahealthcloud.com/demoAPIServer%2Ffhir%2Fr4 or
aud=https%3A%2F%2Facmsptc14762001.devathenahealthcloud.com%3A9443/demoAPIServer%2Ffhir%2Fr4 for authorize URL.

**Comment by deepaktiwari29** [comment]
Hello @GaryHammer701 , hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
