### ISSUE TITLE
Provider login flow callback error after successful login and patient selection- Public key not found: q-23falevZhhD3hm9CQbkP5MQyU

### ISSUE THREAD

**Issue by ankitydvmind24** [GEHealthcare/apiserver.gehealthcare.com#299]
I am using Athena provider flow to log in to the work account. Login is successful, I am able to search and select a patient successfully.

After I have selected a patient, the redirect throws me this error:

error=invalid_client&error_description=Public%20key%20not%20found:%20q-23falevZhhD3hm9CQbkP5MQyU

Note: This error has been occurring since yesterday, earlier everything was working correctly. Is Athena server down or what is the issue?

**Comment by deepaktiwari29** [comment]
Hello @ankitydvmind24,

I am able to get the code and generate token on ap22 sandbox. Were you able to follow the instructions from dev portal and get the appropriate auth code after selecting the patient? If not, can you please post a full copy of the URL you are using for the authorize endpoint.

**Comment by ankitydvmind24** [comment]
Hello @deepaktiwari29 Yes, I checked now ap22 is working now. I was trying with both ap23 and ap22 since last few days and was getting the error.

Thanks for the help.
