### ISSUE TITLE
Error: The provided redirect url is not an approved redirect location.

### ISSUE THREAD

**Issue by sergeiAI** [GEHealthcare/apiserver.gehealthcare.com#300]
During the API setup process, we encountered the following error: "Error: The provided redirect url is not an approved redirect location." However, we cannot set up the redirect URL until the product is fully set up on Athena's platform. Please help.

**Comment by deepaktiwari29** [comment]
Hello @sergeiAI,
Can you please provide the full URL to the authorize endpoint with ClientId and RedirectUri parameters? This may enable us to help you determine the cause of your issue.

**Comment by ctobias84** [comment]
I have forwarded the full URL to you by email thanks.

**Comment by sergeiAI** [comment]
Hi, any update on the resolution of this issue?

**Comment by ctobias84** [comment]
Checking now

Chris Tobias
Senior Manager Operations Enablement and Readiness

[A picture containing logo  Description automatically generated]
Portland, Oregon U.S.
athenahealth.com<https://www.athenahealth.com/>

**Comment by FyrozAhmed** [comment]
Hi sergeiAI , I have reformatted your authorize url authenticating against our aP version 22 FHIR sandbox and shared over email to you. Please try and let us know.

**Comment by deepaktiwari29** [comment]
Hello @sergeiAI , hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
