### ISSUE TITLE
SMART on FHIR workflow 

### ISSUE THREAD

**Issue by vishal-khobare** [GEHealthcare/apiserver.gehealthcare.com#302]
Hi,
 
I currently have an application created (Healow) in the developer portal of Athena. But I was trying to find documentation for EHR launch workflow but couldn't find anything. Could you please point me in the right direction?
 
The existing documentation points to only invoking the authorize endpoint, but in SMART on FHIR launch for EHR launch it calls the launch endpoint first. As per  https://hl7.org/fhir/smart-app-launch/app-launch.html#step-2-launch-ehr    , the launch endpoint format is https://SMART_APP_LAUNCH?iss=xxx&launch=xxx  .  How can I invoke this launch endpoint from Athena dev portal sandbox?
 
Could you please let us know .
 
Thanks

**Comment by deepaktiwari29** [comment]
Hello @vishal-khobare,
Thanks for reaching out to us and sorry for delayed response.
athenaPractice and athenaFlow do support both Standalone and EHR Launch. However, as of right now, there isn't any EHR flow documentation available on our devPortal.
You can check the information in #214 for details about EHR launch with user and patient context and let us know if you need any more information.

**Comment by deepaktiwari29** [comment]
Hello @vishal-khobare, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
