### ISSUE TITLE
PDF support in Athena Practice

### ISSUE THREAD

**Issue by lakshmiunnithan16** [GEHealthcare/apiserver.gehealthcare.com#306]
We need to send assessment scores in a PDF document to Athena Practice after conducting a behavioral assessment test in our client software application. However, we encountered an error indicating that Athena Practice does not support PDF documents.

Your prompt response would be greatly appreciated.

Thank you

**Comment by deepaktiwari29** [comment]
@lakshmiunnithan16 
Please check the information in issue: #262

**Comment by deepaktiwari29** [comment]
Hello @lakshmiunnithan16, hoping we have answered your questions. Marking this issue as closed, if you have any further questions, please open a new ticket.
