### ISSUE TITLE
Athena Practice Integration Questions

### ISSUE THREAD

**Issue by Wugue** [GEHealthcare/apiserver.gehealthcare.com#307]
Hello, 

My team has been working with one of our clients using Athena Practice. We would like to request any information you have about APIs that allow for pushing SOAP note information into discrete fields.

**Comment by deepaktiwari29** [comment]
@Wugue 
athenaPractice and athenaFlow do not yet support any API which could allow pushing SOAP note information as part of any field.

**Comment by deepaktiwari29** [comment]
Hello @Wugue, hoping we have answered your questions. Marking this issue as closed, if you have any further questions, please open a new ticket.
