### ISSUE TITLE
AthenaIDX for Group Management

### ISSUE THREAD

**Issue by roseb-dv** [GEHealthcare/apiserver.gehealthcare.com#308]
Looking for information regarding AthenaIDX for Group Management
What API's are available for this system and is there another name this system currently goes by?

**Comment by deepaktiwari29** [comment]
@roseb-dv 
apiserver-athenaFlex forum provides support for the on premise athenaPractice/athenaFlow (aP/aF) FHIR APIs. Was this question/issue posted on the proper forum?

**Comment by roseb-dv** [comment]
@deepaktiwari29 I'm trying to determine the proper forum. Where can I see the current list of athenaPractice/athenaFlow (aP/aF) FHIR APIs?

**Comment by deepaktiwari29** [comment]
@roseb-dv The configuration & implementation of athenaPractice/athenaFlow (aP/aF) product related to FHIR R4 APIs are listed in below URL:
https://mydata.athenahealth.com/fhirapidoc/r4

**Comment by roseb-dv** [comment]
Thank you.

Is this system typically hosted by Athena or does the practice host the server/database on premise?
________________________________

**Comment by roseb-dv** [comment]
Also, has AthenaIDX for Group Management been rebranded to either athenaPractice/athenaFlow ? or another name?
________________________________

**Comment by deepaktiwari29** [comment]
Hey @roseb-dv ,
Sorry for the delayed response. 

**Is this system typically hosted by Athena or does the practice host the server/database on premise?**
Yes, the practice generally host the server/database on premise.

**Also, has AthenaIDX for Group Management been rebranded to either athenaPractice/athenaFlow ? or another name?**
No, athenaIDX and athenapractice are different products from athenahealth.

**Comment by lindsay-davis-zocdoc** [comment]
Hello @deepaktiwari29 , I am also looking for information about building to AthenaIDX APIs. I was just directed to this forum. If this is not the correct forum for questions about AthenaIDX, can you please direct me to a resource that can assist? We submitted our original queries here (https://www.athenahealth.com/solutions/revenue-cycle-management?utm_salesforce=7016f000001yX2IAAU) and were directed to this forum.

**Comment by deepaktiwari29** [comment]
@lindsay-davis-zocdoc 
For athenaIDX inquires please contact your L1 customer support representative or by logging a case within Salesforce.

**Comment by deepaktiwari29** [comment]
Hello @roseb-dv & @lindsay-davis-zocdoc,
Hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
