### ISSUE TITLE
How to authorize application at the practice level

### ISSUE THREAD

**Issue by jonathanminson** [GEHealthcare/apiserver.gehealthcare.com#309]
We have an application that is working in the sandbox. I have created a "Production" version of the app here:

<img width="503" alt="image" src="https://github.com/user-attachments/assets/fa5a9293-4270-4c09-ac24-d6d5c40139ca">

However, when I attempt to authenticate I get: invalid_client. This makes sense, as I assume there is something the client has to do to enable our application.

Can someone point me in the right direction or provide me documentation?

**Comment by deepaktiwari29** [comment]
Hello @jonathanminson,
Sorry for delayed response. Yes, that's correct. If you have registered your app and marked it as "Production", all you need to do before using it for the Authentication flow is add it to the API App Authorization list from the client.
Please follow this path to add your app in the list:
Home Page> Administration > System > Interoperability > API App Authorization

**Comment by deepaktiwari29** [comment]
Hello @jonathanminson, hoping we have answered your questions. Marking this issue as closed, if you have any further questions, please open a new ticket.
