### ISSUE TITLE
How to query all appointment types

### ISSUE THREAD

**Issue by schlueterryan** [GEHealthcare/apiserver.gehealthcare.com#311]
Is there a good way to query all appointment types? I've been able to get specific ones to be returned from ValueSet api method but only if I already know the code. Thanks!

**Comment by deepaktiwari29** [comment]
Hello @schlueterryan ,
We don't currently support any API function to get all available appointment types. As you have already stated, the ValueSet API can be used to obtain the particular ones upon request with a specific code. 
As of now, we only support this mechanism.

**Comment by deepaktiwari29** [comment]
Hello @schlueterryan, hoping we have answered your questions and you are able to proceed. Marking this issue as closed, if you have any further questions, please open a new ticket.
