### ISSUE TITLE
Appointment Status Writebacks 

### ISSUE THREAD

**Issue by laurenartera** [GEHealthcare/apiserver.gehealthcare.com#312]
We would like to the use the UPDATE on Appointment.participant:Patient.status; accepted values: accepted | declined | tentative | needs-action to facilitate Appt Status writebacks  - 

- Can Athena provide more direction or confirm this approach to appointment status writebacks ? (Are there any alternative API(s) available?)
- For an Appointment UPDATE, does Athena require all appt data elements returned? 
- Can data elements be omitted from the UPDATE to preserve existing values in Athena Practice?
- Does "accepted" == "confirmed"?
- Does "declined" == "patient cancel request"?
- Is there a default appt patient status and, if so, what is it?

**Comment by deepaktiwari29** [comment]
Hello @laurenartera ,
Sorry for the delayed response. As of now there are no alternative APIs that support Appointment related write backs. UPDATE on Appointments are achieved through Appointment API only.
Issues #21 , #108 , #165 have sample request payloads for creating appointments.

To answer your question related to UPDATE on Appointment.participant:Patient.status, as of now we don't support update on this field and we have been showing default value as 'tentative' for Appointment.participant:status.

**For an Appointment UPDATE, does Athena require all appt data elements returned?**
You are not required to send ALL the values while updating an appointment instead you can send only mandatory fields and the field/s you want to update. You can find the mandatory fields for Appointment updates in above mentioned issues.

**Can data elements be omitted from the UPDATE to preserve existing values in Athena Practice?**
Yes.

**Does "accepted" == "confirmed" and "declined" == "patient cancel request"?**
**Is there a default appt patient status and, if so, what is it?**
Yes that's correct. Please find more details here: [link](https://hl7.org/fhir/R4/codesystem-participationstatus.html)
But as said before, we are only supporting 'tentative' for status of participant's.

**Comment by deepaktiwari29** [comment]
Hello @laurenartera, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
