### ISSUE TITLE
 athenahealth login widget is not showing up: I'm getting Error: Invalid client for support service. This client is not configured to use fuzzy

### ISSUE THREAD

**Issue by ronichristian** [GEHealthcare/apiserver.gehealthcare.com#315]
**Describe the bug**

**To Reproduce**
1. Provide necessary credentials on postman
2. Click get access token

**Screenshots**
![image](https://github.com/user-attachments/assets/a9e3570c-6a4f-4ac4-82d9-5323e8b55e7f)

**Comment by deepaktiwari29** [comment]
Hello @ronichristian,
Thank you for reaching out to us. This GitHub forum contains information related to the FHIR APIs for athenaPractice and athenaFlow products.
The issue you stated above seems to be related to a login into athenaNet. If you need assistance using athenaOne APIs, please post your query at https://docs.athenahealth.com/api/support.
