### ISSUE TITLE
Get full list of appointment-service-types

### ISSUE THREAD

**Issue by geoff-bengson-zocdoc** [GEHealthcare/apiserver.gehealthcare.com#318]
**Your question**
Hello,

Is there a way to get a full list of all appointment service types?  I see that you can search these by provider like so: `{{base_url}}/Appointment/$lookup-type?practitioner=1225652472001060`.
I would like to get a full list of these without searching each provider.

**Any background information about this question**

I also see there is a ValueSet with the Id of APPOINTMENTTYPE and SERVICETYPE. example: `{{base_url}}/ValueSet?_id=APPOINTMENTTYPE`
However, neither of these returns the appointment service types. 

Thank you.

**Comment by deepaktiwari29** [comment]
Hello @geoff-bengson-zocdoc 
Thank you for reaching out to us.
Regarding your query, as of now we don't support any API functionality to get all available appointment types. As you have already stated, the ValueSet API can be used to obtain the particular ones upon request with a specific code.

**Comment by deepaktiwari29** [comment]
Hello @geoff-bengson-zocdoc, hoping we have answered your question. Marking this issue as closed, if you have any further questions, please open a new ticket.
