### ISSUE TITLE
Diagnostic Report

### ISSUE THREAD

**Issue by JonTGE** [GEHealthcare/apiserver.gehealthcare.com#5]
Anyone know the rest API to look up the blood lab values?

Please help.

Thank you,

Ahn

**Comment by JonTGE** [comment]
The Centricity API does not support DiagnosticOrder resource type at this time.

The API documentation describes how you can get information about supported operations directly from the API server itself.

https://smartappdocsprod.azureedge.net/http.html#conformance
This describes the conformance statement that every FHIR server must support.  The Conformance resource is acccessed by adding "metadata" to the base URL.

 https://apisandbox.gehealthcare.com:9443/demoAPIServer/metadata
This information indicates which FHIR resources are supported by the API Server and the interactions or operations that are supported for each resource.

 Lab results can be retrieved searching Observation resource by category.  A maximum of 20 resources are returned by default.  You can get more in a single request by using the _count search parameter.
Example:
https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir/Observation?patient=1239620410000620&category=laboratory&_count=100

Thanks,

Torin

**Comment by keithboone** [comment]
A small clarification: 
The API Server DOES NOT support the DiagnosticReport, which would be used to obtain Lab Values in a report.
The API Server DOES support finding requests for Lab Values made in a DiagnosticOrder resource, and also supports finding the actual values by querying for them through the Observation resource.
