### ISSUE TITLE
Try to authorize test app, keep failing with Unknown Client error

### ISSUE THREAD

**Issue by michelemottini** [GEHealthcare/apiserver.gehealthcare.com#7]
The test app is at https://demo.careevolution.com/SMARTest/SMARTest.html - tried to register it a couple of times, copied the client ID but no luck

(The test app can be used by anyone to test connection with any SMART-enabled server)

**Comment by praneetlokege** [comment]
@michelemottini what was the redirect_uri that you registered with the app? Can you please also share some details on what problems you are experiencing while trying to authorize the test app?

**Comment by Torin-Shepard-GE** [comment]
Screenshot of the successful app registration shows the redirect URL in all lower case.  The attempted request to the authorize endpoint has mixed case.

**Comment by praneetlokege** [comment]
@michelemottini you are correct, that the SMART spec doesn't state the need for `id_token` in the `response_type` query-param. Once again, it seems that you have hit an issue with the version of the sandbox server. This also has been addressed in a later version of the API server as well, which will return the `id_token` in the response for the `/token` endpoint without the need for updating your `response_type` for the `/authorize` endpoint. However, it is still valid to send `id_token` in the `response_type` as per the [Hybrid Flow](https://openid.net/specs/openid-connect-core-1_0.html#Authentication). In any case, I will work with our team to update our documentation with the information from this thread.

Also, just as an FYI, please note that, even though we give you back an `id_token` we do not support the Implicit Flow, which would have allowed you to use a one-trip authentication mechanism; a mechanism used by SPAs and Native Clients.

If you are good for now, I will close this issue. Please let us know.

**Comment by michelemottini** [comment]
OK, thanks, closing this

> hit an issue with the version of the sandbox server

Any idea if/when the sandbox server will be updated?
