### ISSUE TITLE
OAuth 'invalid_client' on Token request

### ISSUE THREAD

**Issue by jaydgus** [GEHealthcare/apiserver.gehealthcare.com#8]
Our app successfully brings up the auth page, credentials login and grant, but we get a 500 internal server error response when trying to call the token service: "invalid_client: An unexpected error has occurred. Please try this operation again later"   

Here are the settings we are using:
AuthUrl:  https://apisandbox.gehealthcare.com:9443/demoAPIServer/oauth2/authorize?aud=https://apisandbox.gehealthcare.com:9443/demoAPIServer&response_type=code id_token&client_id={ClientID}&redirect_uri={Callback}&scope={Scope}&state={State}
TokenUrl:  https://apisandbox.gehealthcare.com:9443/demoAPIServer/oauth2/token
CallbackUrl:  {our registered url}
BaseFHIRUrl:  https://apisandbox.gehealthcare.com:9443/demoAPIServer/
Scope:  patient/*.read launch/patient

Is there anything we should be doing differently?

Thank you,
Jay

**Comment by praneetlokege** [comment]
@jaydgus are you able to share the `redirect_uri` for your app?

**Comment by praneetlokege** [comment]
There hasn't been any activity in this thread. I'll go ahead and close this issue. Please re-open if you still have an issue.
