### ISSUE TITLE
PilotFish - Can't Authorize

### ISSUE THREAD

**Issue by brianthannan** [GEHealthcare/apiserver.gehealthcare.com#9]
I've got the api sandbox url working for my account: https://apisandbox.gehealthcare.com:9443/demoAPIServer/oauth2/authorize?state=personal&scope=openid%20profile%20patient/*.read%20launch/patient&response_type=code%20id_token&redirect_uri=https://healthcare.pilotfishtechnology.com&aud=https%3A%2F%2Fapisandbox.gehealthcare.com%3A9443%2FdemoAPIServer&client_id=eyJhbGciOiJSUzI1NiJ9.eyJjbGllbnRfdXJpIjoiaHR0cDpcL1wvaGVhbHRoY2FyZS5waWxvdGZpc2h0ZWNobm9sb2d5LmNvbSIsImdyYW50X3R5cGVzIjpbImF1dGhvcml6YXRpb25fY29kZSJdLCJpc3MiOiJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb20iLCJyZWRpcmVjdF91cmlzIjpbImh0dHBzOlwvXC9oZWFsdGhjYXJlLnBpbG90ZmlzaHRlY2hub2xvZ3kuY29tIl0sInRva2VuX2VuZHBvaW50X2F1dGhfbWV0aG9kIjoiY2xpZW50X3NlY3JldF9iYXNpYyIsInNvZnR3YXJlX2lkIjoiMThSMSIsIm5hdGl2ZV9jbGllbnQiOmZhbHNlLCJodHRwczpcL1wvbXlkYXRhLmdlaGVhbHRoY2FyZS5jb21cL29hdXRoMi5jbGFpbXNcL2FwcF9pZCI6IjNhZDE2MzI1LTdlNTctNDU4Mi04ODhlLWVlMGNhY2JlODU3ZiIsImV4cCI6MTg0NTE0NDg0NiwiY2xpZW50X25hbWUiOiJQaWxvdEZpc2giLCJpYXQiOjE1Mjk1MjU2NDYsImNvbnRhY3RzIjpbImpmbGF2aW5AcGlsb3RmaXNodGVjaG5vbG9neS5jb20iXSwicmVzcG9uc2VfdHlwZXMiOlsiY29kZSJdfQ.aio2WR0Qvsp83yX2VEHtvAk6uBxS4V9e1L2tjJdDRUgNnR3xrGpWL7xwK9Un9fINv8Mq9RwQNaVSQL0FMuPnP4THQAwbfLAvXrt_RNFo76DqYVs5-u2y2y8F9hM3wgbICfiOcpI-Na0BzC4r9GJlqeudLqeBy1KCBtDQ4L8bQYk

That works now. It appears I had misspelled ‘healthcare’ in my first attempt with redirect_uri, and then somehow I got an extra trailing slash in there. All is well with the above url.
 
**However, now it redirects me to a sign in page, but I was expecting to receive a response with token that I could use for successive calls.
     Is there a strategy for dealing with these API calls programmatically when it redirects me to a sign in page?**

**Comment by brianthannan** [comment]
After some reading of the documentation, I now see mention of Azure Active Directory.

Is that something we would have to setup to use the API? If so, how do we go about doing that properly? Do you have documentation on how to do that?

Or is it that GE Centricity uses Active Directory behind the scenes for Authorization?

**Comment by JonTGE** [comment]
Hi Brian,

Thank you for the question.  I'm currently researching the question and will be in contact tomorrow.

Regards,

Jon

**Comment by gitkedar** [comment]
The authorize call should not be done from Postman. Since it is an interactive login, you must do it from the  browser

**Comment by brianthannan** [comment]
The ultimate goal is to call it using our PilotFish application that does a basic HTTP request, very much like Postman.

If it is an interactive login, how should we programmatically get through the login?
Or is it a one-time task that we do in the browser and then use that auth code within the PilotFish application HTTP request?

Is there perhaps a scope parameter value I can use to bypass having to do the interactive login?

---
Brian Hannan
Senior Software Solutions Architect
PilotFish

office: 813.864.8662 x7006
email: bhannan@pilotfishtechnology.com<mailto:bhannan@pilotfishtechnology.com>
skype: bhannan.pilotfish

**Comment by brianthannan** [comment]
I guess I don't understand how it's an API if it requires an interactive login to use.

**Comment by brianthannan** [comment]
Hi,

I’ve posted in the GitHub issues forum again, but I’m not getting responses. Here is my question again:

“The ultimate goal is to call it using our PilotFish application that does a basic HTTP request, very much like Postman. If it is an interactive login, how should we programmatically get through the login? Or is it a one-time task that we do in the browser and then use that auth code within the PilotFish application HTTP request? Is there perhaps a scope parameter value I can use to bypass having to do the interactive login?”

“I guess I don't understand how it's an API if it requires an interactive login to use.”

Can someone please assist in answering my question?

Thanks!

---
Brian Hannan
Senior Software Solutions Architect
PilotFish

office: 813.864.8662 x7006
email: bhannan@pilotfishtechnology.com<mailto:bhannan@pilotfishtechnology.com>
skype: bhannan.pilotfish

**Comment by praneetlokege** [comment]
@brianthannan the type of "login" you are looking to use with PilotFish is what a service-to-service authentication looks like. There is a ["draft" version](http://docs.smarthealthit.org/authorization/backend-services/) of this in the works by the SMART consortium.  However, that is more suitable for headless applications (no UI) that mostly operate in a batch mode. Can you tell us a little bit more about what PilotFish does? There may be a way for you to still integrate with our API through our Partner Program. The link to the program is in our developer portal.

An interactive login is absolutely normal for an API. We use OAuth 2.0 for securing our API using the `authorization_code` grant flow. In this case, the API uses SMART's **standalone launch sequence**, as described on SMART's website [here](http://docs.smarthealthit.org/authorization/). As a side note, the EHR launch sequence does not apply to you, it is for EHR vendors (like our own EHR system) to launch SMART-compliant apps directly from within the EHR.

**Comment by brianthannan** [comment]
Praneet,

Sure, PilotFish is software that runs as a service without a UI (ex: Windows Service). Our clients create what we call ‘interfaces’ that do various tasks, such as make calls out to EMR’s to send/receive data. We create and deploy an interface to the service application. When certain triggers or conditions are met then the interface runs and makes calls to the EMR, and does whatever else that interface needs to do for our client.

For all other EMR/EHR’s we integrate with, there is no interactive login to use their API. This is why it’s somewhat confusing to me.

Any ideas you have for a way around this would be greatly appreciated.

Thanks!

---
Brian Hannan
Senior Software Solutions Architect
PilotFish

office: 813.864.8662 x7006
email: bhannan@pilotfishtechnology.com<mailto:bhannan@pilotfishtechnology.com>
skype: bhannan.pilotfish

**Comment by keithboone** [comment]
Consider when you use applications on your phone, tablet or computer with Facebook or Google Apps or similar applications.  These applications all require an interactive login even though they are all created using APIs.  The base case for FHIR is to support patient facing apps where patients login.  There are other application types where the app runs more like a service, and we have authentication mechanisms that support those without the interactive login, but there is still the need to authenticate and authorize the user.

    Keith

On Jun 26, 2018, at 4:51 PM, brianthannan <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess I don't understand how it's an API if it requires an interactive login to use.

**Comment by SameerSingh1991** [comment]
Closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
